name: "Checking EditorConfig"

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: technote-space/get-diff-action@v3
    - name: Checking EditorConfig
      env:
        VERSION: "2.1.0"
        OS: "linux"
        ARCH: "amd64"
      run: |
        curl -sSf -O -L -C - https://github.com/editorconfig-checker/editorconfig-checker/releases/download/$VERSION/ec-$OS-$ARCH.tar.gz && \
        tar xzf ec-$OS-$ARCH.tar.gz && \
        ./bin/ec-$OS-$ARCH -disable-indentation ${{ env.GIT_DIFF }}
